version: '3'

services:
  galas:
    build:
      context: .
    restart: on-failure
    depends_on:
      - minio
    ports:
      - 8080:8000
    networks:
      - localnet
    env_file: ./dev/.env
  nginx:
    image: nginx:1.15
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - localnet
    depends_on:
      - galas
  minio:
    image: minio/minio:RELEASE.2019-06-04T01-15-58Z
    volumes:
      - ./dev/minio:/export
    ports:
      - 9001:9000
    networks:
      - localnet
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /export
  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #       /usr/bin/mc config host add myminio http://minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
  #       /usr/bin/mc rm -r --force myminio/galas;
  #       /usr/bin/mc mb myminio/galas;
  #       /usr/bin/mc policy download myminio/galas;
  #       exit 0; "
  # postgres:
  #   image: postgres:10
  #   networks:
  #     - localnet
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=docker
  #     - PGDATA=/pgdata
  #   volumes:
  #     - ./dev/db/dbdata:/var/lib/postgresql/db-data
  #     - ./dev/db/init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24